adcp:
  source_directory: ${SVEA_SOURCE_DIR}/adcp
  target_directory: ${SVEA_DATA_DIR}/adcp
ctd:
  source_directory: ${SVEA_SOURCE_DIR}/ctd
  subversion_repo_url: ${SVEA_SVN_REPO}/ctd
ferrybox:
  source_directory: ${SVEA_SOURCE_DIR}/ferrybox
  subversion_repo_url: ${SVEA_SVN_REPO}/ferrybox
  target_directory: ${SVEA_WISKI_DIR}
mvp:
  source_directory: ${SVEA_SOURCE_DIR}/mvp
  subversion_repo_url: ${SVEA_SVN_REPO}/mvp
