[project]
name = "svea_data_manager"
version = "1.0.0"
description = "Python package to archive data from RV Svea"
authors = [
    {name = "", email = "nodc@smhi.se"},
]
dependencies = [
    "click>=8.3.1",
    "pyyaml>=6.0.1",
    "scipy>=1.13.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
gui = [
    "flet>=0.22.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "ruff>=0.14.14",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[project.scripts]
sdm-cli = "svea_data_manager.cli.cli_app:cli"

[tool.ruff]
line-length = 90
indent-width = 4
target-version = "py311"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = [
    "A",   # flake8-builtins
    "F",   # pyflakes
    "E",   # pycodestyle: error
    "W",   # pycodestyle: warning
    "I",   # isort
    "BLE", # flake8-blind-except (disallow broad/blanket except)
    "RUF"  # Ruff-specific rules
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # Allow unused imports in __init__ files