ADCP:
  source_directory: 
  target_directory: C:/mw/temmp/test_sdm/data/file_storage/adcp
  force: true
CTD:
  source_directory: 
  subversion_repo_url: https://sharkdata-svn-utv.smhi.se/repos/sharkdata/data/ctd
  force: true
FERRYBOX:
  source_directory: 
  subversion_repo_url: https://sharkdata-svn-utv.smhi.se/repos/sharkdata/data/ferrybox
  target_directory: C:/mw/temmp/test_sdm/data/wiski
  force: true
MVP:
  source_directory: 
  subversion_repo_url: https://sharkdata-svn-utv.smhi.se/repos/sharkdata/data/mvp
  force: true
